---
title: "AmpSeq_FresnedoScripts2019"
author: "SMGP"
date: "4/7/2021"
output:
  html_document: default
  pdf_document: default
---

# Ampsec Scripts from Fresnedo 2019
Info obtained and modified from https://github.com/JFresnedo/AmpSeq/blob/master/Preliminaries.md

## 1. Initial Singularity and AmpSeq image Setup
These steps are for initial Singularity AmpSeq Setup if you have already done this you skip and go to Step 2

```{bash}
pwd
```

### Changing from home directory to work directory 

<code>cd $WORK<code>

### Creating a working folder  


```{bash eval=FALSE, include=TRUE}
ssh sgabriel@rhino.unl.edu
```


```{bash}
cd AmpSeq1
```



#Cloning repository (containing example and codes)
git clone https://github.com/JFresnedo/AmpSeq.git

#singularity won't load in login node so changing to a working node
srun --nodes=1 --ntasks-per-node=2 --mem-per-cpu=32g --time=2:00:00 --pty $SHELL

#Loading Singularity on the HCC
module load singularity/3.2

#Pulling the container (info from the github and https://singularity-hub.org/collections/2392)
singularity pull --name AmpSeq.sif shub://JFresnedo/AmpSeq:ampseq
# This will generatate the AmpSeq.sif 
to load the container 
singularity shell AmpSeq.sif

#To test open 
vcftools or etc


## 2. Executing AmpSeq and runing provided example
Use the MD files from the github example

